### ISSUE TITLE
N5S用SD卡，刷最新squashfs-sysupgrade无法启动

### ISSUE THREAD

**Issue by limonene0x** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1007]
N5S用SD卡，刷最新squashfs-sysupgrade无法启动，该怎么刷最新版本到SD卡中呢？为什么现在没有sd版本的了？

**Comment by kiddin9** [comment]
https://supes.top/nanopi-r5s%e7%ba%bf%e5%88%b7openwrt%e8%87%b3emmc%e6%95%99%e7%a8%8b/
参考这个教程.

**Comment by limonene0x** [comment]
手头没有公对公USB线，过两天试试。现在是不可以刷到SD卡里，从SD卡启动了吗？

**Comment by kiddin9** [comment]
可以SD卡启动的.直接写入sysupgrade到SD卡中即可.

**Comment by limonene0x** [comment]
可是用balenaEtcher将最新定制r5s-squashfs-sysupgrade.img.gz刷入SD卡之后无法启动，刷回之前的定制r5s_sd.img.gz可以正常启动

**Comment by alan21j** [comment]
r4s有同樣情況，好像裏面缺少了network

**Comment by limonene0x** [comment]
刷包之后分区状态是这样的
![定制固件分区情况](https://user-images.githubusercontent.com/47286271/196837582-80d473ef-e736-4066-949e-25c8a5fda9c3.png)

**Comment by ryan5u3n** [comment]
同问，为什么不出之前的***_sd.img.gz固件了，最近的都是***-squashfs-sysupgrade.img.gz。
体积都差了几倍大小，之前的通过友善官方固件的emmc刷机助手直接刷入emmc，顺利启动，现在的不行了。

**Comment by zealic** [comment]
这个版本的固件有问题 `09.05.2022-openwrt-rockchip-armv8-friendlyarm_nanopi-r5s_sd.img.gz`，刷好以后无法启动。
