### ISSUE TITLE
2022-10-17 尝鲜版本有问题

### ISSUE THREAD

**Issue by BI7PRK** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1014]
- 设备：**R4S**
- 更新：**在线更新 / 下载固件重刷**
- 问题：**不能上网，网口WLAN与LAN的指示灯对调了。而且其中一个指示灯不亮**

#1012

**Comment by czm180** [comment]
我也出现了这种问题
![IMG_20221019_170316](https://user-images.githubusercontent.com/70885963/196647304-cfea530a-7800-4f5b-a6a7-7012b6241da0.jpg)
![IMG_20221019_170321](https://user-images.githubusercontent.com/70885963/196647341-34ee2b33-4430-47a4-8dd2-8b295640a88e.jpg)

**Comment by xeasonwang** [comment]
一样，插LAN口结果WAN灯亮了

**Comment by kiddin9** [comment]
好的,等修复.

**Comment by kiddin9** [comment]
已修复,刷最新的20号的固件
