### ISSUE TITLE
AX9000 160Mhz WiFi 可以搜索到但无法连接

### ISSUE THREAD

**Issue by devioa** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1067]
如题另外想问下，我想修改luci菜单的项目顺序，但是我打开`/usr/lib/lua/luci/controller`里面东西很少，比如`network`和`system`菜单里的项目在这个目录里都没有，想问下是不是改到其他位置去了？ 

还有启动shellclash，提示`iptables v1.8.8 (legacy): Couldn't load match 'owner':No such file or directory`
是不是固件iptables有问题？

**Comment by klcb2010** [comment]
同样  能开启 但不能连接

**Comment by DaiCae** [comment]
同无法连接
