### ISSUE TITLE
能否适配H3C TX1800 Plus系列（TX1800 Plus/TX1801 Plus / TX1806）

### ISSUE THREAD

**Issue by UnknownErrorCodes** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1094]
感谢开发者能提供如此便利的系统，可惜页面里没有H3C TX1800 Plus系列机型的选项，希望添加适配

**Comment by UnknownErrorCodes** [comment]
该系列型号openwrt在8月就已经添加了支持
[https://github.com/openwrt/openwrt/commit/13308161788c98ae6cd48c22b13339fdb8c77130](url)
望适配

**Comment by kiddin9** [comment]
已适配
https://supes.top/?target=ramips%2Fmt7621&id=h3c_tx1800-plus

**Comment by UnknownErrorCodes** [comment]
> 已适配 https://supes.top/?target=ramips%2Fmt7621&id=h3c_tx1800-plus

感谢适配
