### ISSUE TITLE
能否支持友善电子新出的开发板 NanoPi R5C？

### ISSUE THREAD

**Issue by luangong** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1100]
友善电子 11 月底发布了 NanoPi R5C，SoC 跟 R5S/R66S/R68S 一样是 RK3568，价格比较亲民，作为主路由是个不错的选择。

相比 R5S：

- 只有两个 2.5G 网口（少了一个千兆网口）
- 不支持 NVMe SSD
- 内存和 eMMC 容量也不一样

但相比电犀牛 R66S：

- 有铝合金外壳散热，CPU 满载温度仅 51℃ 左右
- 多了 HDMI 口，方便断网时进控制台调试诊断
- 可选扩展 M.2 Wi-Fi 模块

参考链接：

- [友善电子推出双 2.5G 网口迷你开发板 NanoPi R5C，售价 349 元起](https://www.ithome.com/0/657/562.htm)
- https://www.friendlyelec.com/index.php?route=product/product&product_id=290
- https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R5C

**Comment by kiddin9** [comment]
好的,

**Comment by kiddin9** [comment]
已添加R5C支持
https://supes.top/?target=rockchip%2Farmv8&id=friendlyarm_nanopi-r5c

**Comment by luangong** [comment]
神速啊，赞👍

**Comment by i11cn** [comment]
亲，亲测定制出来的ROM启动失败

**Comment by kiddin9** [comment]
> 

有可能只是灯不亮,接上电脑试试.

**Comment by bg7pge** [comment]
没有看到R5C的选项啊

**Comment by i11cn** [comment]
LAN口接电脑，接上uart线，能进入console，检查网络，定制ROM时指定的ip地址都没设置成功，所以不能给电脑分配IP，FriendlyWRT就能正常工作，所以我觉得应该是某些配置项有问题
12月9日的那个ROM和我自己定制的ROM都是这样的现象

**Comment by i11cn** [comment]
很抱歉能提供的信息不多，因为当时急着用，看了一眼之后就刷了FriendlyWRT用上了
我尽量过几天把它换下来，那时再记录一下错误信息之类的发出来

**Comment by anschein** [comment]
> 已添加R5C支持 https://supes.top/?target=rockchip%2Farmv8&id=friendlyarm_nanopi-r5c

大神我定制了R5C的固件刷进去，目前发现的问题一个是指示灯不亮，只有电源灯工作，另外一个是M.2 WIFI无法工作，有需要的话我帮忙抓日志

**Comment by bearcolin** [comment]
M.2 无线网卡系统设备没有列出，单独安装了rtl8822ce-firmware驱动包也不行，官方固件网络设备里是有wlan0设备的，这个固件里没有。不知道是不是需要手动设置？
