### ISSUE TITLE
小米4a千兆版 ssr plus无法启动

### ISSUE THREAD

**Issue by kkkbook** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1129]
手动启动都不行
[root@OpenWrt:18:28 ~] # /etc/init.d/shadowsocksr restart
flock: (null): Bad file descriptor
rm: '/tmp/ssrplus/bin' is a directory

**Comment by kiddin9** [comment]
已修复.

**Comment by itsHenry35** [comment]
我的还是无法启动，不知道大佬是怎么解决的
[root@OpenWrt:23:39 ~] # /etc/init.d/shadowsocksr restart
flock: (null): Bad file descriptor

**Comment by kkkbook** [comment]
> 我的还是无法启动，不知道大佬是怎么解决的 [root@OpenWrt:23:39 ~] # /etc/init.d/shadowsocksr restart flock: (null): Bad file descriptor

ssh输入/etc/init.d/shadowsocksr start
