### ISSUE TITLE
缺少 kmod-nft-compat 组件

### ISSUE THREAD

**Issue by QindongHu** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1136]
360v6硬件，OpenWrt 10.18.2022 by Kiddin' / LuCI Master git-b3b7bca版本，安装SQM的时候，提示缺少kmod-nft-compat 关联组件
![image](https://user-images.githubusercontent.com/108777159/209520918-7e896f3c-b032-4b25-87da-54b658d87d7d.png)

**Comment by QindongHu** [comment]
![image](https://user-images.githubusercontent.com/108777159/209521312-a788ab14-a883-4748-9774-1616f9caefcd.png)

**Comment by Franinc** [comment]
安装wman3时缺少kmod-nft-compat和kmod-nft-fullcone两个
用的是已构建好的固件，看起来没启用nftables，wman3用着好像也没问题？

**Comment by QindongHu** [comment]
不清楚哦，没有用wan3多播均衡负载，就是单线，但是想用sqm，结果提示没有这个插件

**Comment by QindongHu** [comment]
今天再尝试安装sqm，依赖里面没有这个插件了，应该是插件升级解决了这个问题了
