### ISSUE TITLE
自带的xray可能有内存泄露的问题

### ISSUE THREAD

**Issue by anerg2046** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1176]
在MTK7621的CR6608上，如果用定制的passwall2和xray，那么很快内存会爆掉。

目前我处理的方式是删除原有的xray，然后从新在软件包那里安装xray。这样以后内存占用一直在100M附近，不会像默认的那样，直接占到200M+

**Comment by laaArmy** [comment]
提交错地方了，找Xray去
