### ISSUE TITLE
默认科学切换为passwall，bypass是准备弃用不维护了吗？

### ISSUE THREAD

**Issue by Doctorlee0827** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1209]
可惜了，一键通的科学插件。此外最新固件可能是内核原因，无论是OTA升级和全新升级，都有重启后自动还原的bug，重刷回去上一版本就可以保存了，没有日志，因为是主路由忘记导出了。

**Comment by qbenny** [comment]
passwall用不来，我也恢复到上一版本了

**Comment by Tony-N2** [comment]
哪里还能定制上1版本，我的不小心删了。

我也喜欢bypass
