### ISSUE TITLE
r5s aria2插件无法启动，请修复

### ISSUE THREAD

**Issue by underlaw** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1246]
定制版， aria2插件无法启动，请修复。谢谢
![image](https://user-images.githubusercontent.com/33020405/222884658-2194a335-c509-4f89-8922-c3a91d8cc773.png)

**Comment by wpsdoo** [comment]
不要用自带的源安装aria2.版本有问题。下载官方版本的aria2安装可以用。作者没时间修复
