### ISSUE TITLE
X86 PPPOE无法拨号

### ISSUE THREAD

**Issue by veik** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1277]
不管是定制，还是非定制的最新版本，都没办法拨号，退回老版本可以，换其他固件也可以。请教如何解决这个问题

**Comment by yzxj3180** [comment]
定制固件也进不去后台，无法将定制内容合并到固件中，比如后台密码等

**Comment by 110120787** [comment]
我也遇到了这个问题

**Comment by veik** [comment]
换其他固件，或者以前版本都没有问题。真是奇怪了，不知道哪里错了。

**Comment by veik** [comment]
MTU改为1440就可以了
