### ISSUE TITLE
 【已修复】红米AX6 定制2023/1/16内核5.15.94 的【wifi失联】

### ISSUE THREAD

**Issue by digiw** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1315]
下述问题作者已在5.15.106内核的4月新版发布里修复！

内核版本：5.15.94
故障现象：无线信号能被移动设备搜索到，一旦连接就会提示无法连接。观察“系统日志：内核日志” 发现大量报错如下：
--------------------------------------------------------------------------
[   53.694703] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   53.694727] ath11k c000000.wifi: failed to extract mgmt rx event
[   53.697234] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   53.697254] ath11k c000000.wifi: failed to extract mgmt rx event
[   53.705501] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   53.705521] ath11k c000000.wifi: failed to extract mgmt rx event
[   58.709627] ath11k_warn: 2132 callbacks suppressed
[   58.709653] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   58.709669] ath11k c000000.wifi: failed to extract mgmt rx event
[   58.710923] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   58.710945] ath11k c000000.wifi: failed to extract mgmt rx event
[   58.711444] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   58.711464] ath11k c000000.wifi: failed to extract mgmt rx event
[   58.712078] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   58.712097] ath11k c000000.wifi: failed to extract mgmt rx event
[   58.714761] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   58.714787] ath11k c000000.wifi: failed to extract mgmt rx event
[   63.715308] ath11k_warn: 2240 callbacks suppressed
[   63.715347] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   63.715360] ath11k c000000.wifi: failed to extract mgmt rx event
[   63.722121] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   63.722134] ath11k c000000.wifi: failed to extract mgmt rx event
[   63.728153] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   63.728165] ath11k c000000.wifi: failed to extract mgmt rx event
[   63.728590] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   63.728601] ath11k c000000.wifi: failed to extract mgmt rx event
[   63.729190] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   63.729201] ath11k c000000.wifi: failed to extract mgmt rx event
[   68.732492] ath11k_warn: 2162 callbacks suppressed
[   68.732515] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   68.732531] ath11k c000000.wifi: failed to extract mgmt rx event
[   68.733061] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   68.733073] ath11k c000000.wifi: failed to extract mgmt rx event
[   68.738423] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   68.738437] ath11k c000000.wifi: failed to extract mgmt rx event
[   68.746239] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   68.746259] ath11k c000000.wifi: failed to extract mgmt rx event
[   68.746857] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   68.746863] ath11k c000000.wifi: failed to extract mgmt rx event
[   73.744842] ath11k_warn: 2274 callbacks suppressed
[   73.744866] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   73.744880] ath11k c000000.wifi: failed to extract mgmt rx event
[   73.749997] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   73.750005] ath11k c000000.wifi: failed to extract mgmt rx event
[   73.750606] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   73.750613] ath11k c000000.wifi: failed to extract mgmt rx event
[   73.752989] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   73.752997] ath11k c000000.wifi: failed to extract mgmt rx event
[   73.756245] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   73.756253] ath11k c000000.wifi: failed to extract mgmt rx event
[   78.762477] ath11k_warn: 2288 callbacks suppressed
[   78.762524] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   78.762537] ath11k c000000.wifi: failed to extract mgmt rx event
[   78.767632] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   78.767659] ath11k c000000.wifi: failed to extract mgmt rx event
[   78.768305] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   78.768314] ath11k c000000.wifi: failed to extract mgmt rx event
[   78.770572] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   78.770584] ath11k c000000.wifi: failed to extract mgmt rx event
[   78.774143] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   78.774161] ath11k c000000.wifi: failed to extract mgmt rx event
[   83.770934] ath11k_warn: 2370 callbacks suppressed
[   83.770978] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   83.770990] ath11k c000000.wifi: failed to extract mgmt rx event
[   83.777765] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   83.777798] ath11k c000000.wifi: failed to extract mgmt rx event
[   83.778453] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   83.778465] ath11k c000000.wifi: failed to extract mgmt rx event
[   83.782908] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   83.782940] ath11k c000000.wifi: failed to extract mgmt rx event
[   83.785307] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   83.785327] ath11k c000000.wifi: failed to extract mgmt rx event
[   88.778161] ath11k_warn: 2420 callbacks suppressed
[   88.778202] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   88.778214] ath11k c000000.wifi: failed to extract mgmt rx event
[   88.786739] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   88.786752] ath11k c000000.wifi: failed to extract mgmt rx event
[   88.797745] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   88.797761] ath11k c000000.wifi: failed to extract mgmt rx event
[   88.802818] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   88.802831] ath11k c000000.wifi: failed to extract mgmt rx event
[   88.803661] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   88.803674] ath11k c000000.wifi: failed to extract mgmt rx event
[   93.785575] ath11k_warn: 2450 callbacks suppressed
[   93.785614] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   93.785626] ath11k c000000.wifi: failed to extract mgmt rx event
[   93.788753] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   93.788769] ath11k c000000.wifi: failed to extract mgmt rx event
[   93.789918] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   93.789933] ath11k c000000.wifi: failed to extract mgmt rx event
[   93.801612] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   93.801645] ath11k c000000.wifi: failed to extract mgmt rx event
[   93.818252] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   93.818265] ath11k c000000.wifi: failed to extract mgmt rx event
[   98.794131] ath11k_warn: 2412 callbacks suppressed
[   98.794171] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   98.794184] ath11k c000000.wifi: failed to extract mgmt rx event
[   98.795005] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   98.795018] ath11k c000000.wifi: failed to extract mgmt rx event
[   98.795375] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   98.795388] ath11k c000000.wifi: failed to extract mgmt rx event
[   98.803254] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   98.803267] ath11k c000000.wifi: failed to extract mgmt rx event
[   98.806406] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[   98.806418] ath11k c000000.wifi: failed to extract mgmt rx event
[  103.811812] ath11k_warn: 1974 callbacks suppressed
[  103.811829] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[  103.811844] ath11k c000000.wifi: failed to extract mgmt rx event
[  103.812651] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[  103.812658] ath11k c000000.wifi: failed to extract mgmt rx event
[  103.813107] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[  103.813115] ath11k c000000.wifi: failed to extract mgmt rx event
[  103.820869] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[  103.820877] ath11k c000000.wifi: failed to extract mgmt rx event
[  103.822603] ath11k c000000.wifi: invalid length in mgmt rx hdr ev
[  103.822610] ath11k c000000.wifi: failed to extract mgmt rx event
-----------------------------------------------------------------------------
因此推测可能与openwrt内核或者ath11k的固件文件有关，经上一版本的网友分享了，能正常连接wifi的固件版本里分享的相关wifi驱动文件和wifi固件文件，我做了一些替换测试，最终发现手动替换无法修复问题，具体可见 issues #1243 

还得请作者亲自出手，顺便一起修复ax6 网口无法正常显示，和cpu超频模块中缺失的频段情况。（具体可见 issues #1243）

感谢！！

**Comment by harry0071** [comment]
+1，我也是能搜到wifi，但是却连不上
