### ISSUE TITLE
ax6定制固件 内核版本 5.15.109 wifi问题（5.15.112新版已修复）

### ISSUE THREAD

**Issue by digiw** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1346]
Kiddin' / LuCI Master git-2c00316--内核版本 | 5.15.108
刚刚从106升级到108，查看系统日志和内核日志发现本在106修复的wifi问题又出现；具体表现为识别路由器，wifi硬件，但是当手机等移动设备连接到路由器后，没等多久，设备的wifi连接就不断的连接，断开这样的循环。

**Comment by digiw** [comment]
补充内核日志信息，关于wifi信号不断重置的部分内容：
[ 1621.501289] br-lan: port 3(phy1-ap0) entered blocking state
[ 1621.501316] br-lan: port 3(phy1-ap0) entered disabled state
[ 1621.501614] device phy1-ap0 entered promiscuous mode
[ 1632.630102] IPv6: ADDRCONF(NETDEV_CHANGE): phy1-ap0: link becomes ready
[ 1632.630384] br-lan: port 3(phy1-ap0) entered blocking state
[ 1632.630404] br-lan: port 3(phy1-ap0) entered forwarding state
[ 1645.106725] br-lan: port 3(phy1-ap0) entered disabled state
[ 1645.778287] br-lan: port 3(phy1-ap0) entered disabled state
[ 1645.825923] device phy1-ap0 left promiscuous mode
[ 1645.825950] br-lan: port 3(phy1-ap0) entered disabled state
[ 1646.242862] br-lan: port 3(phy1-ap0) entered blocking state
[ 1646.242886] br-lan: port 3(phy1-ap0) entered disabled state
[ 1646.243350] device phy1-ap0 entered promiscuous mode
[ 1646.243482] br-lan: port 3(phy1-ap0) entered blocking state
[ 1646.243495] br-lan: port 3(phy1-ap0) entered forwarding state
[ 1646.244105] br-lan: port 3(phy1-ap0) entered disabled state
[ 1657.233795] IPv6: ADDRCONF(NETDEV_CHANGE): phy1-ap0: link becomes ready
[ 1657.234074] br-lan: port 3(phy1-ap0) entered blocking state
[ 1657.234095] br-lan: port 3(phy1-ap0) entered forwarding state
[ 1666.108911] br-lan: port 3(phy1-ap0) entered disabled state
[ 1666.528554] br-lan: port 3(phy1-ap0) entered disabled state
[ 1666.586024] device phy1-ap0 left promiscuous mode
[ 1666.586057] br-lan: port 3(phy1-ap0) entered disabled state
[ 1667.137079] br-lan: port 3(phy1-ap0) entered blocking state
[ 1667.137100] br-lan: port 3(phy1-ap0) entered disabled state
[ 1667.137403] device phy1-ap0 entered promiscuous mode
[ 1678.145562] IPv6: ADDRCONF(NETDEV_CHANGE): phy1-ap0: link becomes ready
[ 1678.145929] br-lan: port 3(phy1-ap0) entered blocking state
[ 1678.145954] br-lan: port 3(phy1-ap0) entered forwarding state
[ 1757.126737] br-lan: port 3(phy1-ap0) entered disabled state
[ 1757.458779] br-lan: port 3(phy1-ap0) entered disabled state
[ 1757.536110] device phy1-ap0 left promiscuous mode
[ 1757.536139] br-lan: port 3(phy1-ap0) entered disabled state
[ 1758.152325] br-lan: port 3(phy1-ap0) entered blocking state
[ 1758.152353] br-lan: port 3(phy1-ap0) entered disabled state
[ 1758.152654] device phy1-ap0 entered promiscuous mode

**Comment by harry0071** [comment]
我也遇到了升级到5.15.109后wifi频繁断连的问题
幸好我还留着5.15.106的固件包
我暂时从5.15.109降级到5.15.106后wifi就没出现频繁断连的问题了

**Comment by digiw** [comment]
> 我也遇到了升级到5.15.109后wifi频繁断连的问题 幸好我还留着5.15.106的固件包 我暂时从5.15.109降级到5.15.106后wifi就没出现频繁断连的问题了

恩，还在等修复，暂时接了ap

**Comment by digiw** [comment]
5.15.112新版已经修复！
