### ISSUE TITLE
从01.10.2023更新到04.18.2023时，所有已安装的软件和配置都丢失了

### ISSUE THREAD

**Issue by snowinner** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1349]
非常确认在更新时勾选了“保持设置，保留当前配置”和“保留已安装软件包”，但更新完后全部丢失，回到默认状态
硬件：NanoPi R4SE

**Comment by ATErBion** [comment]
可能是因为这次引入了istore，变动很大，还好升级前有备份

**Comment by xenstar** [comment]
> It is very confirmed that "Keep settings, keep current configuration" and "Keep installed software packages" were checked during the update, but they were all lost after the update and returned to the default state Hardware: NanoPi R4SE

It's always like that. You have basically two options

1) Don't upgrade if everything is working smoothly.
2) Keep backup, then compile from supes.top and then flash in the memory card directly.
