### ISSUE TITLE
升级 23.05-SNAPSHOT - 05.30.2023，passwall 跟 mwan3 会冲突

### ISSUE THREAD

**Issue by t894924815** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1391]
设备：R86S
具体表现是局域网内设备可以访问国内网站，不能翻，op本身dns解析会失败，关闭mwan3，reboot之后能正常使用

**Comment by hhyuanyi** [comment]
reboot是什么

**Comment by t894924815** [comment]
已经找到原因了，尝试 dig baidu.com，结果是：
`;; communications error to 100.100.100.100#53: timed out. dns`
所以尝试卸载了下 tailscale，果然好了
