### ISSUE TITLE
你们到底在代码里下了什么毒?

### ISSUE THREAD

**Issue by DUWENINK** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1392]
你们的代码更新一次炸一次,后台流量飙满,卡的进不去后台?你们莫非在那我的openwrt挖矿?

**Comment by DUWENINK** [comment]
> 可能是bug 如果不是系统bug就是你后装插件的原因 好像更新保留插件的话 它是更新完再从服务器从新下载安装的 这时候又要部署插件又要下载东西 肯定是又卡又跑流量

抱歉,可能是我表述有问题 整整一天以20MB/S的速度上传

**Comment by kiddin9** [comment]
这种纯粹发泄情绪的帖子有什么意义? 代码都是开源的, 我无法自证不存在的东西, 提供证据(找出有毒的代码,抓包上传的网站,找出挖矿的程序)才有讨论的价值, 否则就是捣乱和诬陷.

**Comment by liusha1010** [comment]
已经赞助了永久会员

**Comment by liusha1010** [comment]
山上那个 dchp那个挖矿进程，和固件本身有关么？
