### ISSUE TITLE
该项目编译的openwrt在双isp情况下外网访问udp，只有其中一个公网能联通

### ISSUE THREAD

**Issue by ciskonc** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1418]
类似问题 

https://github.com/openwrt/openwrt/issues/12929

https://github.com/openwrt/packages/issues/9538#issuecomment-1150592803

https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8294493&page=1#pid18741745

**Comment by delgh1** [comment]
Not a bug report, should be closed
