### ISSUE TITLE
（8-30编译已修复）AX6 定制固件无法正常启动（ 分支: 23.05.0-rc3 内核: 5.15.127） 

### ISSUE THREAD

**Issue by digiw** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1521]
官网定制最新版本分支: 23.05.0-rc3 内核: 5.15.127（web服务器选择：uhttpd），
刷入固件后ax6只恒亮一个蓝灯，主机无法自动获取dhcp分配ip；
改用uboot刷入对应同版本文件，症状同上！ 

在保持定制选项没变的情况下，刷入前一个版本 OpenWrt 23.05.0-rc2 (08.04.2023) 内核：5.15.118，固件启动正常！

**Comment by ooyyee** [comment]
最近的固件老是有这个问题

**Comment by soongzi** [comment]
刷最新固件 (08.23) 时 AX6 出现的问题与主帖的一模一样。刷回上一版后 AX6 恢复正常了。

**Comment by hongyunfei** [comment]
我在原版op升级刷入的，也是长亮一个蓝灯，开始以为刷砖了，主机无法自动获取dhcp分配ip，后来发现能连上wifi，进入后台后发现网口配置里面都没有绑定网口，手动设置后可以正常使用。

**Comment by digiw** [comment]
8月30日重新官网编译的版本已经修复！
