### ISSUE TITLE
最近更新的openvpn-server端使用问题

### ISSUE THREAD

**Issue by 656567543** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1541]
最近更新了openvpn-server新增了很多功能，之前的直接参数填好，下载配置文件就行了，现在这个版本要手动生成证书，好不容易证书生成完了，客户端还连接不了，有没有哪位大神知道怎么使用啊。

**Comment by now163** [comment]
你好。这个问题解决了吗？我看在/etc下面有一个生成证书的openvpncert.sh脚本。但运行会报错，里面的pkitool、build-dh、clean-all命令找不到。
