### ISSUE TITLE
Redmi AX6: 5GHz Wi-Fi becomes unstable after upgrading

### ISSUE THREAD

**Issue by nanonya** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1551]
之前使用的是 2023 年上半年的某个版本。
更新到 09.25.2023 后，5 GHz Wi-Fi 极不稳定，一般情况是连接上后只有数秒可以访问互联网或路由器 Web 页面，随后掉线。调整信道、通道宽度、功率均无法解决。日志暂时没有看到异常情况。
2.4 GHz Wi-Fi 没有该问题。
降级 07.12.2023 无法解决，更早版本则已不提供下载下载。

**Comment by ltpop** [comment]
同AX6，目前刷过近几个月（6、7、8、9月）的版本，发现都有些问题。
有的是网格接口图示不显示；无线信号扫描页为空白；甚至无wifi信号。
目前用回06.08.2023的自编译版本，比较稳定，但软件包不敢更新，可能会出现升级后无wifi或连接不上的问题

**Comment by nanonya** [comment]
10.01.2023 版本，似乎已经解决，再观察几天。

**Comment by Tobylei** [comment]
解决了吗？

**Comment by ltpop** [comment]
尝试升级到了10.15.2023，目前正常了。

**Comment by nanonya** [comment]
亲测新版固件问题已解决。
