### ISSUE TITLE
openwrt.ai打开极其缓慢，编译固件卡在“索取固件”这一步

### ISSUE THREAD

**Issue by windrunner337** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1602]
已经好几天了，多久可以恢复呀，永久赞助了

建议给vip弄个单独服务器，按月付费或者按次付费都愿意，现在这样真是憋死个人

折腾半天没编译成功，还提示每日10次的限额用完

**Comment by Holuke** [comment]
我连注册都卡住了

**Comment by ooyyee** [comment]
我的能登录,不编译新的固件,只显示以往编译的.
