### ISSUE TITLE
x86定制固件Firewall4无法打开全锥形NAT

### ISSUE THREAD

**Issue by Aethersailor** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1622]
定制的x86固件使用Firewall4的情况下，无法通过TurboACC启动全锥形NAT，不管是兼容模式还是性能模式都不行
但是定制的R2S固件则可以正常启动全锥形NAT
对比两个设备中安装的软件包，发现x86定制固件中缺少了kmod-nft-fullcone，补全这个模块以后重新定制，仍然无法启动nat

**Comment by windrunner337** [comment]
尝试定制了用旧版Firewall的版本，则可以正常打开全锥形NAT
