### ISSUE TITLE
定制固件的在线升级功能是不能用了吗？

### ISSUE THREAD

**Issue by Aethersailor** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1650]
手头四台设备均刷写的去年定制的固件，无法检测和升级到最新的2月份固件，想问一下这是可能是什么原因？
![image](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/22260104/4c8918a2-ab0c-4173-960c-be93cfa7dfb8)

**Comment by 9thChasingWindGirl** [comment]
先更新软件源和软件包，看看配置的地址还能访问吗

**Comment by Karwyn** [comment]
![op](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/12808116/71c41baf-02ae-4daf-b37d-3f21d2df6ecb)
我最新的都没有在线升级选项了

**Comment by windrunner337** [comment]
> 先更新软件源和软件包，看看配置的地址还能访问吗

配置的地址是openwrt.ai，可以正常访问的

**Comment by 9thChasingWindGirl** [comment]
> > 先更新软件源和软件包，看看配置的地址还能访问吗
> 
> 配置的地址是openwrt.ai，可以正常访问的

自行下载固件升级吧
