### ISSUE TITLE
Lunzn FastRhino R66S 0306版本固件无法获取ip

### ISSUE THREAD

**Issue by it-glen** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1682]
Lunzn FastRhino R66S 0306版本固件做二级路由，lan口插上网线与电脑连接，电脑无法获取ip，手动修改ip也无法进入后台

**Comment by AsherZhu** [comment]
r5s也是一样的问题，刷机完毕后lan接口接在电脑无反应灯也不亮

**Comment by rumianoesa** [comment]
试试不插wan，只lan接电脑能不能获取ip打开后台
我的情况是一插上wan就会卡死，卡死了自然就无法分配dhcp了

**Comment by it-glen** [comment]
> 试试不插wan，只lan接电脑能不能获取ip打开后台 我的情况是一插上wan就会卡死，卡死了自然就无法分配dhcp了

0317版本固件，R66s已回复正常
