### ISSUE TITLE
Lunzn FastRhino R66S，lan口无法分配ip

### ISSUE THREAD

**Issue by it-glen** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1764]
Lunzn FastRhino R66S，正常刷入固件后无法进入后台，交换两根网线位置后可进入后台，但是lan口无法实现dhcp功能，修改lan配置br-lan为eth0后可以分配ip，但是一些功能无法正常使用。
![image](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/73119626/1f456a4d-c34a-4ae7-9c11-47088e0051bc)

**Comment by master-yun-yun** [comment]
应该是存在这个问题。我现在是在ap上设置dhcp服务器，正常了
