### ISSUE TITLE
似乎能获取到ipv6地址，但无法使用ipv6

### ISSUE THREAD

**Issue by zoope** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1789]
![2](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/21034891/059cf69c-90dc-4b44-a05b-5c675e706c44)
![1](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/21034891/4204e0bc-3d66-4d15-b173-b2314a88bb68)

我用路由器直接拨号开启ipv6是能使用的，光猫应该没问题
没有什么头绪，该怎么排查？

**Comment by KardRi** [comment]
你應該把wan_6擺到 wan的那個zone，把wan6那個刪除或先把他挪出wan的zone

**Comment by sky540** [comment]
我最近我也发现这个问题

**Comment by zoope** [comment]
> 你應該把wan_6(灰色的)擺到wan的那個zone(紅色的，與pppoe-wan同一個顏色)，把wan6(最下面那個)刪除或先把他挪出wan的zone，然後看你們是nat66還是有delegate可以用

不太清楚要怎么操作 我把wan6删了 并且在“设置向导”里把启用ipv6打开了 还需要别的设置吗

**Comment by KardRi** [comment]
> > 你應該把wan_6(灰色的)擺到wan的那個zone(紅色的，與pppoe-wan同一個顏色)，把wan6(最下面那個)刪除或先把他挪出wan的zone，然後看你們是nat66還是有delegate可以用
> 
> 不太清楚要怎么操作 我把wan6删了 并且在“设置向导”里把启用ipv6打开了 还需要别的设置吗

選wan_6的編輯->防火牆設置->選紅色的wan

**Comment by zoope** [comment]
> > > 你應該把wan_6(灰色的)擺到wan的那個zone(紅色的，與pppoe-wan同一個顏色)，把wan6(最下面那個)刪除或先把他挪出wan的zone，然後看你們是nat66還是有delegate可以用
> > 
> > 
> > 不太清楚要怎么操作 我把wan6删了 并且在“设置向导”里把启用ipv6打开了 还需要别的设置吗
> 
> 選wan_6的編輯->防火牆設置->選紅色的wan

我试过 但是这个wan_6无法编辑 只能去wan里面修改
![image](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/21034891/ccc628ef-3304-4da3-b55c-015be7b9fcd5)

**Comment by zoope** [comment]
@KardRi 我搞定了 非常感谢
@sky540 你弄好了吗 我参照上面的思路 想办法把wan_6加到wan的防火墙zone里 
![屏幕截图 2024-07-08 192909](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/21034891/8573614d-45ab-4884-9d80-fd88501ce162)
我是在高级设置里添加了`list network 'wan_6'`这一条 其他设置都不改，你也可以参考一下
