### ISSUE TITLE
[ 提问 ] 红米ax5（Xiaomi RM1800）内置无线吗？

### ISSUE THREAD

**Issue by huajideshutiao** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#1823]
我在没扩容的机子里刷了之后没有无线选项，是空间足够就行了吗？

**Comment by xibeilang0616** [comment]
### **刷好固件后，第一件事情就是重启，重启后无线就出来了。**

**Comment by huajideshutiao** [comment]
> ### **刷好固件后，第一件事情就是在管理界面里点重启，重启后无线就出来了。**

试了下，确实是控件问题，空间不够会自动裁剪。
