### ISSUE TITLE
DDNS 内添加的服务不能自动启动

### ISSUE THREAD

**Issue by cmbrun** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#553]
DDNS 内添加的服务不能自动启动，必须每次开机后手工点RELOAD才行

**Comment by lucktu** [comment]
你说的是不能自动更新（服务器的IP）吧？

不过我不用这个，我做旁路用。

**Comment by cmbrun** [comment]
是DDNS这个程序可以启动，但是里面添加的具体某项DDNS服务不能自己启动，关机或重启后状态就变成了未运行，需要手工点reload才能运行服务

**Comment by fantasylidong** [comment]
这个我也碰到了，请问openwrt更新哪个分区不会被清除，准备写脚本解决ddns问题了

**Comment by gatalon** [comment]
我也遇到了同样的问题。

**Comment by keyboydg** [comment]
我也是遇到了同样问题，不会解决~~~

**Comment by antenna2008** [comment]
系统 ->  启动项  ->  本地启动脚本

                在exit 0 之前写入
                
                /etc/init.d/ddns restart
