### ISSUE TITLE
R2S 上行带宽问题

### ISSUE THREAD

**Issue by gee1k** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#744]
你好，
目前 R2S 固件在不交换网口的情况下上传速度会被限制在10M左右，代理只有5M，下载速度没有问题。交换网口过后上传下载均恢复正常（100M）。
前几天在TG反馈过这个问题，刚刚看到有新版本固件。更新过后发现问题还在，特地来留给 Issue，等你有空的时候可以看看是什么问题！

然后顺带提一个另外的问题，刚刚在系统内部在线更新的时候选择了保存配置和保留插件，但是更新过后插件并没有自动安装恢复。特地等了很久，而且 opkg 并没有在占用。后自己手动重新安装插件，大部分配置倒的确还在（AdGuardHome的配置没了）

> 直连测速

![telegram-cloud-photo-size-5-6131781082169848674-y](https://user-images.githubusercontent.com/12059800/173338264-83fb98a0-8058-409c-8a3e-7eacc6c5b82a.jpg)

> 代理测速

![telegram-cloud-photo-size-5-6131781082169848675-y](https://user-images.githubusercontent.com/12059800/173338212-57731497-712a-48f4-b85c-54bdef7bd7cb.jpg)

**Comment by gee1k** [comment]
经过多次测试发现：直连情况下上传速度也不是完全是 10M 左右，有时候会出现测速刚开始时上传速度跑到 100M 左右，然后在一两秒钟之内急速下降到50M以下。

代理情况下多次测试一直是5M。


----------

交换网口后直连和代理均能稳定在 100 ~ 120 M

**Comment by kiddin9** [comment]
装个 luci-app-homebox 内网测速试试

**Comment by gee1k** [comment]
上次测试的时候，用 iperf 正向、反向分别测试了，是没问题的。

我再用这个插件试试

**Comment by gee1k** [comment]
luci-app-homebox 测试正常

<img width="941" alt="image" src="https://user-images.githubusercontent.com/12059800/174047489-6038cfd0-ca7e-47fe-b409-bec5b2dc5448.png">


SpeedTest
<img width="762" alt="image" src="https://user-images.githubusercontent.com/12059800/174047584-7c666a61-6424-40fa-a58c-a5c383b17a3f.png">



交换网口后

<img width="756" alt="image" src="https://user-images.githubusercontent.com/12059800/174048118-5576287a-0f06-40d6-912b-e73dbe2b4823.png">

**Comment by gee1k** [comment]
但是我刚刚升级了最新版固件后，在不交换网口的情况下直连测速的上传速度好像有所提升，之前是 10M 左右。现在能跑到 50 ~ 80 左右，有时候也能上 100M。代理情况下还是不行。

所以也不知道是不是 OpenClash 的问题，但是交换网口后都没问题，所以很奇怪
