### ISSUE TITLE
AX6更新地址链接错误重复"ipq807x/"导致无法在线更新

### ISSUE THREAD

**Issue by flyalpaca** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#747]
提示无法更新然后显示了一个链接
![QQ截图20220614120510](https://user-images.githubusercontent.com/64674924/173492071-7ba4ff55-4ec3-41e8-8161-5924f92b5015.png)
手动打开链接显示404
https://op.supes.top/firmware/ipq807x/ipq807x/redmi-ax6/06.13.2022-openwrt-ipq807x-generic-redmi_ax6-squashfs-nand-sysupgrade.bin
![QQ截图20220614120531](https://user-images.githubusercontent.com/64674924/173492090-41787d03-974c-472e-8080-fa2ba93a07ea.png)
链接中出现了两个ipq807x/
去掉一个后可以正常下载
https://op.supes.top/firmware/ipq807x/redmi-ax6/06.13.2022-openwrt-ipq807x-generic-redmi_ax6-squashfs-nand-sysupgrade.bin
希望早日修复

**Comment by kiddin9** [comment]
感谢反馈.  已修复, 软件包中更新下 luci-app-gpsysupgrade 或者下载最新固件重刷即可.
