### ISSUE TITLE
IPv6中继模式失败

### ISSUE THREAD

**Issue by xw-yin** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#753]
中继模式配置完成之后设备可以获取IPv6地址，但是IPv6test测试失败，也无法访问IPv6网站。奇怪的是我把配置备份恢复到其他固件居然成功了就很奇怪。

**Comment by kiddin9** [comment]
关闭梯子再测试看看.

**Comment by xw-yin** [comment]
关了还是不行

**Comment by xw-yin** [comment]
还有一个bug就是文件管理的文件列表，这个版本显示不出来，但是上个版本就可以。

**Comment by xw-yin** [comment]
![image](https://user-images.githubusercontent.com/9315129/174083953-fedb732a-dd71-48bd-bdd3-ee40cc3ff533.png)
我说的是这里，我记得上个版本这里是显示文件夹的列表的。

**Comment by kiddin9** [comment]
是这里,我的正常显示,

**Comment by xw-yin** [comment]
![image](https://user-images.githubusercontent.com/9315129/174085363-58e59297-1215-4e2d-a266-b78ee7692eaa.png) 
我甚至用手机浏览器也试了还是没有，这是我的设备和固件信息。

**Comment by xuebkgithub** [comment]
ipv6 nat 模式下.需要自定义 路由表.你自定义了嘛

**Comment by xw-yin** [comment]
不是nat 是relay

**Comment by xuebkgithub** [comment]
你用中继的时候.dns获取到了吗?  另外一定要关闭梯子和各种代理
你贴下.你的dhcp 和 naetwork

**Comment by xw-yin** [comment]
![image](https://user-images.githubusercontent.com/9315129/174300192-05c91452-db82-45d8-bccc-00e41ea14ffb.png)
![image](https://user-images.githubusercontent.com/9315129/174300250-0336ef47-5a4a-48f8-ad29-6fce1881d5f8.png)

**Comment by xw-yin** [comment]
config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option ednspacket_max '1232'
	option port '53'
	option dns_redirect '1'
	option allservers '1'
	option min_ttl '3600'
	option cachesize '8192'
	option dnsforwardmax '8192'
	option localservice '0'
	option rebind_protection '0'
	option noresolv '1'
	list server '127.0.0.1#7874'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	option force '1'
	option ra 'relay'
	option dhcpv6 'relay'
	option ndp 'relay'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'
	option ra 'relay'
	option dhcpv6 'relay'
	option ndp 'relay'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

config dhcp 'wan6'
	option interface 'wan6'
	option ignore '1'
	option ra 'relay'
	option dhcpv6 'relay'
	option ndp 'relay'
	option master '1'

**Comment by xw-yin** [comment]
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option packet_steering '1'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth1'
	list ports 'eth2'
	list ports 'eth3'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option ipaddr '192.168.2.1'

config interface 'wan'
	option device 'eth0'
	option proto 'dhcp'
	option ipv6 'auto'

config interface 'wan6'
	option proto 'dhcpv6'
	option device 'eth0'
	option reqaddress 'try'
	option reqprefix 'auto'

**Comment by xuebkgithub** [comment]
我看你的电脑截图里面.是已经获取到ipv6了啊. 地址.和dns都正常啊.
你用 traceroute6 6.ipw.cn 看下你的路由可以行走吗?
下图是我正常的
![CleanShot 2022-06-17 at 20 49 32@2x](https://user-images.githubusercontent.com/41730586/174301622-99161a90-f455-4176-bba4-02d3aac57b4f.png)

**Comment by xw-yin** [comment]
![image](https://user-images.githubusercontent.com/9315129/174302146-7cd1e506-c403-4ceb-a6b2-6f432370a2c0.png)

**Comment by xuebkgithub** [comment]
你关闭翻墙.(增强模式.设置系统代理.).在关闭ipv4只保留ipv6 自动获取.  这样的话.你获取到ipv6地址了吗.

**Comment by xuebkgithub** [comment]
你删除 option ip6assign '60'

**Comment by xuebkgithub** [comment]
你ping6 你的网关, 路由器.和路由器dhcp ipv6获取到的自己.看下通不通

**Comment by xw-yin** [comment]
我路由搞了内网穿透  你登录看下
xw-yin.icu:8003
密码 123456

**Comment by xw-yin** [comment]
ping6 路由地址是可以的

**Comment by xw-yin** [comment]
我换个固件试试吧

**Comment by xuebkgithub** [comment]
刚到家.还没来得及回你

**Comment by xw-yin** [comment]
刚刷的别人的5.15内核的固件也不行，但是刷的5.10的固件就可以

**Comment by xuebkgithub** [comment]
刚刚把你的路由器 去掉了option ip6assign '60'  并且重启了下.你在看下

**Comment by xw-yin** [comment]
![image](https://user-images.githubusercontent.com/9315129/174318096-661c5331-2369-45dc-a41e-77bcce9fc906.png)

**Comment by xuebkgithub** [comment]
你在看下呢?

**Comment by xw-yin** [comment]
这次直接连公网ipv6地址也没了

**Comment by xuebkgithub** [comment]
又调整了下.再不行的话.你就换成 nat6把

**Comment by xuebkgithub** [comment]
你电脑现在 分配到ipv6地址了吗?

**Comment by xw-yin** [comment]
还是不行 刚看了下openwrt的issue也有同样问题，没办法了，辛苦了，谢谢

**Comment by xw-yin** [comment]
https://github.com/openwrt/openwrt/issues/9881

**Comment by xuebkgithub** [comment]
要不你换成nat6模式?

**Comment by xw-yin** [comment]
算了不搞了，内网穿透也够用了，什么时候搞个国内服务器体验应该比IPv6还好，毕竟国内大多都没有公网IPv6环境也访问不了。

**Comment by xw-yin** [comment]
zerotier 设备还要装客户端，手机上还要用vpn模式运行太麻烦了，还是frp方便。

**Comment by xw-yin** [comment]
![image](https://user-images.githubusercontent.com/9315129/174332120-13419ab0-18f1-4ae9-988b-af077f7850ce.png)
![image](https://user-images.githubusercontent.com/9315129/174332237-9d5dcbab-e26b-486f-9846-e4fd28838b0e.png)
![image](https://user-images.githubusercontent.com/9315129/174332280-119e15bd-d67b-489a-98fc-466e983d6796.png)
直接把备份恢复到这个固件就有ipv6公网了，应该是openwrt源码有什么变动。

**Comment by dmlt** [comment]
一样的情况，电脑分配到了ipv6公网ip，能解析ipv6 地址，就是ping6不通。

**Comment by xuebkgithub** [comment]
转发.搞一下
#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=99
STOP=15
interface_public="wan6"
res=`ip -6 route | grep "default from"`
gateway=`echo $res | awk '{print $5}'`
interface=`echo $res | awk '{print $7}'`
start() {
    ip -6 r add default via $gateway dev $interface
    ip6tables -t nat -A POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
}

stop() {
    ip6tables -t nat -D POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    ip -6 r del default via $gateway dev $interface
}
