### ISSUE TITLE
现在多LAN口怎么绑定啊？

### ISSUE THREAD

**Issue by HUiTHEME** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#770]
![6A25887E5BDEDBBBA631C126CB3BBD1B.jpg](https://s2.loli.net/2022/06/22/Ik1eNYBCFMaTxOm.jpg)

![6EDCDEF9E4A74B7B62EEB375C551A585.jpg](https://s2.loli.net/2022/06/22/xqDF8csMHbrfnRS.jpg)

首先描述一下，黑色截图是现在最新的op内核，白色截图是很旧的一个op内核。

问题：白色截图里，在设置LAN口的时候，去到物理接口里  多选勾选 即可把 eth1 eth2 eth3 eth4 eth5 都绑定上。但是，在黑色截图里，在LAN口的端口绑定上，只能是单选，无法多选，选eth1就不能选eth2，选eth2就不能选eth1，如何才能多选多个端口呢？很是疑惑

**Comment by kiddin9** [comment]
![image](https://user-images.githubusercontent.com/48883331/174989459-9093e2ba-24b9-4c46-a71d-6b37bf548319.png)

**Comment by HUiTHEME** [comment]
感谢 感谢  找到了
