### ISSUE TITLE
passwall的分流规则没办法新增

### ISSUE THREAD

**Issue by roxsky** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#779]
如图中所示的地方，输入名字后点添加没有任何反应，chrome和firefox浏览器都试过。我也在passwall那边发过issue，那边说是固件问题。快一年了，一直到最新的固件都有这个问题。

![160085433-2bdbd7bb-fe28-44e2-9956-eb8e6c79d53d](https://user-images.githubusercontent.com/4097168/175381032-3866150a-454b-4136-a1af-c3e10c0d9c7f.png)

**Comment by kiddin9** [comment]
是主题的问题, 换bootstrap或者Argon没问题.

**Comment by roxsky** [comment]
> 是主题的问题, 换bootstrap或者Argon没问题.

换了argon主题确实可以了，也谢谢你开发的固件，真的很好用。
