### ISSUE TITLE
软件包加入qemu-ga/open-vm-tools后并没有安装进固件

### ISSUE THREAD

**Issue by kanned1079** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#782]
手动输入没有提示，常用软件包里选择后也没安装进固件
![image](https://user-images.githubusercontent.com/58361983/175480791-a5fdbd9b-231e-49cd-b2d7-1d4b8a2933bc.png)

**Comment by kiddin9** [comment]
已修复, ctrl+F5强制刷新下浏览器

**Comment by kanned1079** [comment]
> 已修复, ctrl+F5强制刷新下浏览器

谢谢带佬
