### ISSUE TITLE
frps luci界面貌似不能用了，红米ax6

### ISSUE THREAD

**Issue by slslll** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#787]
主页下载的固件
![image](https://user-images.githubusercontent.com/38198381/176904478-cf9b51bf-b91f-4737-bf89-7fa192c10d2f.png)

然后在软件库中安装frps包如下
![image](https://user-images.githubusercontent.com/38198381/176904709-1d5f31ef-43b0-4569-92d2-3fd5e7cbe857.png)

如图，frps界面中没有看到具体设置选项
![image](https://user-images.githubusercontent.com/38198381/176904241-9aed4e98-aad9-472f-bca3-d9bde4e7fcd2.png)
![image](https://user-images.githubusercontent.com/38198381/176904278-e3681a66-e14d-481e-a7a0-c010559368f9.png)

**Comment by kiddin9** [comment]
已修复. 更新软件列表后重装luci-app-frps

**Comment by slslll** [comment]
好像没有变化，是我哪里没操作对吗

1
![image](https://user-images.githubusercontent.com/38198381/176978734-00cd3e08-7c72-4aa7-b7b1-dc79fad77cc3.png)

2
![image](https://user-images.githubusercontent.com/38198381/176978747-84687354-213c-4449-838a-20b1146c68fc.png)

3
![image](https://user-images.githubusercontent.com/38198381/176978777-b3646ef1-e4e8-43a9-9ab6-95daa454bc30.png)


> 已修复. 更新软件列表后重装luci-app-frps

**Comment by slslll** [comment]
难道是源的问题

**Comment by slslll** [comment]
直接用主页定制化固件，这下可以了，感谢作者

**Comment by yu1chaofan** [comment]
![image](https://user-images.githubusercontent.com/32660987/214512691-4e8896d8-572b-48b0-b33c-2f678cb2bcde.png)
![image](https://user-images.githubusercontent.com/32660987/214512712-ac267299-7d21-431c-a6a7-b61c52b2451c.png)

同样显示不出来 
x86平台  固件是2022.11.28 以后的固件

**Comment by zhibinlin1** [comment]
R2S遇到同样问题
