### ISSUE TITLE
X86作旁路由模式下，上网正常，但是每天早上QQ无法登录，重启软路由解决。

### ISSUE THREAD

**Issue by eshop366** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#789]
[用的X86做的旁路由，每天早上无法登录QQ，但是网页和其他应用可以正常联网，重启主路由无法解决，尝试重启软路由后故障排除，每天早上都这样
![微信截图_20220702113635](https://user-images.githubusercontent.com/75906307/176985311-61690ff7-8de4-4d22-8606-a5141732c2d6.png)
![未标题-1](https://user-images.githubusercontent.com/75906307/176985337-ac5e135d-5435-4f86-aef2-bbf6a3113ecc.jpg)

**Comment by dolphin738** [comment]
有没有开AdGuard Home插件

**Comment by eshop366** [comment]
> 有没有开AdGuard Home插件

没有开AdGuard Home，用的smartDNS，但是出现无法登陆QQ时候，重启了smartDNS仍无济于事，只有重启整个软路由才生效。

**Comment by eshop366** [comment]
> 有没有开AdGuard Home插件

没有开AdGuard Home，用的smartDNS，但是出现无法登陆QQ时候，重启了smartDNS仍无济于事，只有重启整个软路由才生效。
