### ISSUE TITLE
后台登陆 默认跳转 /admin/system/initsetup 页面的问题

### ISSUE THREAD

**Issue by lanhailin** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#790]
使用的线自定义编译，Web服务器 Nginx，版本 22.03.0-rc4，内核: 5.15.45

电脑上用浏览器登陆固件后台，每次都会自动跳转到  op/admin/system/initsetup 设置向导这个页面，是否可以在完成设置并保存之后，重新登陆不再跳转设置向导这个页面？可以跳转 /luci/admin/status/overview 系统概览
或者是在哪里可以自己修改为跳转页面？

非常感谢。

**Comment by kiddin9** [comment]
正常来说, 只有网络不通的情况下,才会跳转到设置向导.

**Comment by lanhailin** [comment]
> 

感谢回复。我是做旁路网关，网络确定是通的，opkg更新、后台的 网络/网络诊断 ping openwrt.org 也 正常。每次登陆后台仍然跳转 设置向导页面。

**Comment by kiddin9** [comment]
你的op旁路由没设置lan口DNS吗

**Comment by lanhailin** [comment]
看了一下LAN的DNS，确实是留空的，改为主路由的IP之后，再登陆就不会跳设置向导了。感谢。
