### ISSUE TITLE
概览上的一些小错误

### ISSUE THREAD

**Issue by HUiTHEME** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#797]
![显示小异常](https://s2.loli.net/2022/07/09/fwWDzM1uL97x5J3.png)

**Comment by neobar** [comment]
我也遇到了类似的问题，每次重启，“定制版”三个字就增加一次。

**Comment by HUiTHEME** [comment]
随着重启的次数越来越多，定制版  这三个字  已经重复出现8次了

**Comment by kiddin9** [comment]
已修复, 重新定制.
