### ISSUE TITLE
got error for the new version luci-app-bypass in X86

### ISSUE THREAD

**Issue by edwin19861218** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#816]
Seems some related components error or missing. Is there a free way to install the last correct version?

Plz check the detail output when re-installing.
 
Installing luci-app-bypass (git-22.190.50904-8006ace) to root...
Downloading https://op.supes.top/packages/x86_64/kiddin9/luci-app-bypass_git-22.190.50904-8006ace_all.ipk
Configuring luci-app-bypass.
cfg203db7
Too many arguments

And the error log is:

2022-07-15 16:35:14 SSR server: Shadowsocks Server1 Started!
2022-07-15 16:35:14 Socks5 Node: Can't find VMESS program, start failed!
2022-07-15 16:35:14 Main Node: Can't find VMESS program, start failed!

**Comment by kiddin9** [comment]
Reedit node or update nodes subscription.

**Comment by edwin19861218** [comment]
U r right, thanks
