### ISSUE TITLE
在没有编译进固件时，frps界面在软件包管理安装后无法使用

### ISSUE THREAD

**Issue by slslll** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#818]
显示不了任何选项
![image](https://user-images.githubusercontent.com/38198381/179335794-752dacda-1fb4-4626-989f-f5a9954d9a19.png)
不知道是不是个例

**Comment by kiddin9** [comment]
把 /etc/config/frps 文件删掉后, 重装 luci-app-frps

**Comment by slslll** [comment]
> 把 /etc/config/frps 文件删掉后, 重装 luci-app-frps

好的，谢谢作者
