### ISSUE TITLE
定制固件部分配置无效

### ISSUE THREAD

**Issue by XYZliang** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#819]
官网赞助后自定义固件，后台地址密码，拨号账户密码没用，刷入后还是默认的10.0.0.1和root密码，br-lan也没有拨号是默认的dhcp，要手动配置。

**Comment by XYZliang** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/59312540/179360884-7a46fbbf-02f3-4322-a900-463ecacd72ae.png">
主机名似乎也没生效
<img width="951" alt="image" src="https://user-images.githubusercontent.com/59312540/179360900-1cc0f139-b94d-4a9c-98ec-e9b8722f8bbd.png">

**Comment by kiddin9** [comment]
主机名不要用`这种特殊字符

**Comment by XYZliang** [comment]
> 主机名不要用`这种特殊字符

原来如此，我明天重新试试
