### ISSUE TITLE
n1盒子，upnp打不开

### ISSUE THREAD

**Issue by wunnnn1** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#832]
![image](https://user-images.githubusercontent.com/42443650/180374768-ffb879ea-58a9-47bc-811c-5037e4c342db.png)
我只增加了几个插件，改了管理地址，没有删除任何插件，他好像在提示找不到某些东西

**Comment by wunnnn1** [comment]
这是系统版本
![image](https://user-images.githubusercontent.com/42443650/180375608-0a8c3eec-6aee-4e36-b366-cf7508d27eea.png)

**Comment by kiddin9** [comment]
重新定制, 昨天的版本upnp是有问题, 已经修复了.

**Comment by wunnnn1** [comment]
感谢，已经可以了
