### ISSUE TITLE
R5S定制自定义后台IP刷写后后台显示Not Found

### ISSUE THREAD

**Issue by limonene0x** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#839]
定制R5S版本自定义了IP，刷写后访问后台地址，自动跳转到 `IP/luci/` 并显示 `Not Found` 。
![Snipaste_2022-07-26_15-59-25](https://user-images.githubusercontent.com/47286271/180954902-a14e7c7a-b3d8-4b25-9583-4cf2f1e33aac.png)

**Comment by kiddin9** [comment]
已修复,重新定制下.

**Comment by limonene0x** [comment]
感谢！已解决
