### ISSUE TITLE
X86  自动重启

### ISSUE THREAD

**Issue by 656567543** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#844]
X86    更新了7.12版本之后每个2-4个小时会自动重启，上一个版本没这种情况
CPU    J4125   -8g    I225-V B3

**Comment by jk0106** [comment]
这个版本同样遇到这个问题，每天都在等更新
CPU J4125 RTL8125B

**Comment by XYZliang** [comment]
我有的时候遇到这种问题，也就只能不保留配置重新刷固件，然后配置的时候小心一点。。。。。。
不过最新固件我遇到一个每天固定时间点重启一次的bug，后来排查发现是Watchcat导致了重启，关闭就好了。

**Comment by jk0106** [comment]
好像是新固件加进去的，我记得我没有安装这个插件，卸载试试看

**Comment by 656567543** [comment]
> 我有的时候遇到这种问题，也就只能不保留配置重新刷固件，然后配置的时候小心一点。。。。。。 不过最新固件我遇到一个每天固定时间点重启一次的bug，后来排查发现是Watchcat导致了重启，关闭就好了。

感谢，问题应该解决解决了，就是这个新版的插件默认带了一个ping  网路不通自动重启的规则
