### ISSUE TITLE
N1 电脑无法进入后台，手机可以

### ISSUE THREAD

**Issue by RoyLiu04** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#847]
选用nginx作为网页插件，在windows10自带的edge上输入正确的密码会直接重新加载登陆页面，在iphone的safari中输入正确的密码可以登陆进后台页面。

试着更改过windows的ip，还是不行。在edge的开发者模式里可以看到一次302重定向和一次403 forbidden, 请问问题是出在哪里呢？

**Comment by kiddin9** [comment]
应该是电脑浏览器缓存的问题, 用浏览器隐身模式试试,

**Comment by RoyLiu04** [comment]
> 

用隐身模式进去了，我再试试清除浏览器缓存，刚才可能没有清楚彻底吧，非常感谢
