### ISSUE TITLE
请求支持Gl-iNet B1300

### ISSUE THREAD

**Issue by xkww3n** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#850]
设备信息：<https://openwrt.org/toh/gl.inet/gl-b1300>
OpenWRT官方和LEDE均对此设备有官方支持

**Comment by kiddin9** [comment]
已支持 https://supes.top/?version=22.03&target=ipq40xx%2Fgeneric&id=glinet_gl-b1300
