### ISSUE TITLE
刚复盘了下出现无限重启的原因很奇怪

### ISSUE THREAD

**Issue by xw-yin** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#858]
我刷了好多包都解决问题，最终结束无限重启的一个包无线是没有开启的，一旦我开启无线有设备连接后就会重启然后紧接着无限重启。无线应该是出问题了。

**Comment by xw-yin** [comment]
5G是获取不到IP 2.4G是连上就无限重启

**Comment by kiddin9** [comment]
好的,感谢测试.

**Comment by xw-yin** [comment]
尝试恢复官方固件失败，感觉是无线模块出问题了，还是寄回官方维修吧。
