### ISSUE TITLE
进主页报错

### ISSUE THREAD

**Issue by misakajialin** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#870]
/usr/lib/lua/luci/controller/nextcloud.lua:3: module 'luci.model.docker' not found:
	no field package.preload['luci.model.docker']
	no file './luci/model/docker.lua'
	no file '/usr/share/lua/luci/model/docker.lua'
	no file '/usr/share/lua/luci/model/docker/init.lua'
	no file '/usr/lib/lua/luci/model/docker.lua'
	no file '/usr/lib/lua/luci/model/docker/init.lua'
	no file './luci/model/docker.so'
	no file '/usr/lib/lua/luci/model/docker.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/nextcloud.lua:3: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1153: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1254: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:644: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:893: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:488: in function </usr/lib/lua/luci/dispatcher.lua:487>

我没有修改任何文件，刷完就这样。并且无法连接ssh

**Comment by kiddin9** [comment]
定制的时候加上luci-app-dockerman试试.
