### ISSUE TITLE
hk1box无法u盘启动

### ISSUE THREAD

**Issue by WanQingGit** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#880]
想问怎么刷入呢，刷入优盘后并不会进入刷入的系统，盒子已经刷了armbian，amlogic-s9xxx-openwrt可以正常启动

**Comment by kiddin9** [comment]
修复了下, 下载最新固件重刷试试.

**Comment by WanQingGit** [comment]
嗯，我试了下可以，不过型号不对，只要改一下boot的uEnv.txt就可以了。
