### ISSUE TITLE
反复触发opkg update

### ISSUE THREAD

**Issue by kunger97** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#885]
使用的是红米ax6，今天进行的自定义构建，并刷入。
通过观察htop命令发现opkg update不断重复执行
![QQ截图20220815182750](https://user-images.githubusercontent.com/1808555/184619909-a7dfdf0d-e333-4f00-8ae8-db794f035267.png)

**Comment by kiddin9** [comment]
看起来时nss_packages这个库找不到而卡住了,我修复下.
