### ISSUE TITLE
歌华链无法进入管理页面，只能ssh

### ISSUE THREAD

**Issue by KingBillSame** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#886]
#!/usr/bin/lua
require "luci.cacheloader"
require "luci.sgi.cgi"
luci.dispatcher.indexcache = "/tmp/luci-indexcache"
luci.sgi.cgi.run()

重置了路由器，试过网页无论是uhttpd还是nginx都会下载一个“下载”的文件，这是里面的内容。

**Comment by kiddin9** [comment]
使用uhttpd的话, 后台地址是 10.0.0.1/cgi-bin/luci

**Comment by KingBillSame** [comment]
> 

进去了，可能是浏览器缓存没清，后面又正常了
