### ISSUE TITLE
华硕ACRH17 无法使用拨号上网

### ISSUE THREAD

**Issue by 5993zzz** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#887]
输入宽带账号密码后上不了网，重启光猫和路由器都没用。

**Comment by kiddin9** [comment]
有拨号成功么, 后台 网络->网络诊断 中测试下网络

**Comment by 5993zzz** [comment]
> 有拨号成功么, 后台 网络->网络诊断 中测试下网络

ping了www.baidu.com可以通，路由器的灯也显示连上了网，但是wifi和接网线都没网。

**Comment by kiddin9** [comment]
已修复,重新定制下即可.

**Comment by 5993zzz** [comment]
> 已修复,重新定制下即可.

重刷了，问题已解决，辛苦了
