### ISSUE TITLE
定制固件系统项下没有“定制系统升级”

### ISSUE THREAD

**Issue by squallir** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#892]
首先感谢作者的自动编译平台，很方便，已赞助。
遇到一个小问题就是定制完固件全新刷写后，怎么在系统项下找不到“定制系统升级”这一项
因为有时候有增减插件的需求，每次都要重新定制再上传再升级很麻烦
![屏幕截图 2022-08-20 020934](https://user-images.githubusercontent.com/80194322/185681965-396b8288-516f-4d1a-90e8-7b60e6a5c22b.png)

**Comment by kiddin9** [comment]
感谢支持, 定制的时候加上 luci-app-attendedsysupgrade 插件即可.

**Comment by squallir** [comment]
明白了，感谢回复
