### ISSUE TITLE
x86-Openclash-更新订阅配置不改变运行配置

### ISSUE THREAD

**Issue by Franky18** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#912]
Openclash版本：0.45.51-215

x86架构Openclash更新订阅后，订阅文件本身会改变，但运行配置不会改变，因此实际运行时并没有使用新的配置文件。自动、web界面手动、ssh手动：/usr/share/openclash/openclash.sh 更新订阅，都存在此问题。 

自动、ssh手动重启：/etc/init.d/openclash restart 2>/dev/null，openclash也不会更新运行配置。

只有web界面在openclash主页最下方，手动关闭openclash，再开启openclash才会更新运行配置。

不清楚这个问题是openclash的问题还是固件问题，如有冒犯请见谅。

**Comment by Franky18** [comment]
刚刚在自己用lean大源码编译的最新固件上测试了一下，Openclash版本：0.45.51-beta（应该与215是同版吧），也有同样问题，因此应该是Openclash的问题，与固件无关。

本人刚接触Openclash，不清楚Openclash此前版本是否也存在此问题，目前暂时使用Openwrt自动重启来解决。

感谢Kiddin的自动编译，已赞助，感谢！

**Comment by kiddin9** [comment]
感谢支持~

**Comment by Franky18** [comment]
再次感谢Kiddin！

**Comment by Franky18** [comment]
再次感谢Kiddin！

**Comment by Franky18** [comment]
破案了，配置文件订阅命名不能有空格，供有同样问题的用户参考。
