### ISSUE TITLE
感谢大佬的自定义固件，关于京东云RE-SP-01B系统存储空间问题

### ISSUE THREAD

**Issue by kerncoola** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#914]
<img width="1195" alt="iShot2022-08-29 22 33 13" src="https://user-images.githubusercontent.com/13283995/187226499-a1cb5ee3-067e-45ae-8207-b4a20f042607.png">
<img width="1130" alt="iShot2022-08-29 22 33 02" src="https://user-images.githubusercontent.com/13283995/187226509-c239ee2b-d570-4906-aef6-55ef6c5864c0.png">

系统安装后软件包安装空间只有10多兆，无限宝自带64G内置存储，能不能利用上，我也试过后期挂在到overlay中，但多次重启后进不去系统，想着系统安装时就分好区更稳吧。

谢谢。

**Comment by kerncoola** [comment]
<img width="1158" alt="iShot2022-08-29 22 54 59" src="https://user-images.githubusercontent.com/13283995/187230794-d17dcf9a-688b-4278-9b1e-7ff0ad2d6365.png">

**Comment by kiddin9** [comment]
这个内置存储只能通过挂载为其他分区使用,要作为overlay的话比较麻烦,你可以参考esir相关的视频.
https://www.youtube.com/watch?v=YwbwzuXKNlg

**Comment by kerncoola** [comment]
OK
