### ISSUE TITLE
upnp在使用Firewall4(nftables)的情况下无法正常工作（x86）

### ISSUE THREAD

**Issue by pzqpeter** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#920]
upnp在使用Firewall4(nftables)的情况下无法正常工作（x86），而且upnp使用Firewall的情况下虽然可以映射端口，但是不显示正在映射的设备。
![Snipaste_2022-09-02_00-39-08](https://user-images.githubusercontent.com/53438642/187967715-a6a6c9e9-8750-469a-9692-f10d3690224d.png)
![Snipaste_2022-09-02_00-38-50](https://user-images.githubusercontent.com/53438642/187967730-e838c366-df06-4faa-a6a7-310c58806b17.png)

**Comment by XYZliang** [comment]
很早的问题了，不然你以为为什么定制的时候不是默认选择Firewall4的

**Comment by pzqpeter** [comment]
upnp使用Firewall的情况下虽然可以使用，但是不显示正在映射的端口。这个该怎么做呢？
