### ISSUE TITLE
兆能zn-m2是不支持uboot刷入吗

### ISSUE THREAD

**Issue by kerncoola** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#924]
兆能zn-m2、360V6、红米AX5都是同款芯片，使用官方提供的底包`08.07-ZN_M2-SQUASHFS-NAND-FACTORY.UBI`通过uboot刷入无法启动。
<img width="533" alt="image" src="https://user-images.githubusercontent.com/13283995/188297819-92e4bfa5-2d73-4123-a622-88c7868dbd3a.png">

**Comment by refined-fish** [comment]
同问题，求问哥们怎么解决的？
