### ISSUE TITLE
MobiPromo星际宝盒 CM520-79F 没有无线功能，希望修复

### ISSUE THREAD

**Issue by slslll** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#926]
如图，安装好后没有显示无线选项
![image](https://user-images.githubusercontent.com/38198381/188351366-b8805227-e012-4954-900c-e62be390c27f.png)

**Comment by kiddin9** [comment]
试试09.05的最新固件.

**Comment by slslll** [comment]
> 试试09.05的最新固件.

好的我试试

**Comment by slslll** [comment]
> 试试09.05的最新固件.

新版本的无线可以用了，谢谢
![image](https://user-images.githubusercontent.com/38198381/189263434-37a59560-3b6c-4fc3-89d9-c043a863b5c2.png)
