### ISSUE TITLE
Xiaomi Redmi Router AX6S默认源里的N2N插件,静态路由表功能无效

### ISSUE THREAD

**Issue by dolphin738** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#928]
Xiaomi Redmi Router AX6S 默认软件源里的N2N是 https://op.supes.top/packages/aarch64_cortex-a53/n2n_3.0-1_aarch64_cortex-a53.ipk   这个版本,但是这个版本的配置静态路由表功能是无效的,反而是   https://op.supes.top/packages/aarch64_cortex-a53/old/n2n_3.0-3_aarch64_cortex-a53.ipk    这个版本所有功能都是有效的.

**Comment by kiddin9** [comment]
已替换为 n2n_3.0-3_aarch64_cortex-a53.ipk
