### ISSUE TITLE
supes.top自定义的固件设置问题

### ISSUE THREAD

**Issue by ThingsWhy** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#943]
你好，请问supes.top网站自定义固件能不能生成没有“针对国内特殊环境等的自定义优化”的固件，因为之前习惯自己去点这些，所以想着还自己点，但是现在固件自带部分设置，有时候记忆就有些混乱了

**Comment by dolphin738** [comment]
你的意思是生成不带Bypass插件的固件吗?

**Comment by ThingsWhy** [comment]
> 你的意思是生成不带Bypass插件的固件吗?

不是这个意思，比如说，如果我在自定义插件的时候如果选择了adg，之前我自己编译一个固件，使用时如果要用adg会一步一步的设置web端口、adg的dns端口之类的，大佬的固件是直接生成好了现成的配置，其他某些插件也类似默认好了配置，因为原来都是自己点的，突然生成好了有些不习惯，所以想问下能否去掉这些
