### ISSUE TITLE
大雕貌似修复nss ecm (ipq807x，5.15)

### ISSUE THREAD

**Issue by AXBNG** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#950]
大佬可否抽空测试下，感谢

https://github.com/coolsnowwolf/lede/commit/fc1df36dc1e3ab95b2b47d72f9a0c4b06ef0ac41
https://github.com/coolsnowwolf/lede/commit/1003232a7055c5db182335b169b0ce2ecb7eed9a

**Comment by digiw** [comment]
那ax系列就有盼头了！期待更新

**Comment by Pacio** [comment]
看了一下lede的iss，目前还是编译不通过的阶段，所以这边也不能合并

**Comment by AXBNG** [comment]
> 看了一下lede的iss，目前还是编译不通过的阶段，所以这边也不能合并

确实，继续等待吧......
