### ISSUE TITLE
官网op.supes.top证书已过期未自动续签

### ISSUE THREAD

**Issue by dawn-lc** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#961]
![chrome_pnaXeqb07D](https://user-images.githubusercontent.com/30336566/191515150-7f0383f8-79df-47fc-9a72-da21b0f90278.png)

**Comment by kiddin9** [comment]
已修复.

**Comment by dawn-lc** [comment]
![image](https://user-images.githubusercontent.com/30336566/191520212-0f5f223e-7dd9-4603-8bfb-d750d29123e1.png)

**Comment by dawn-lc** [comment]
![image](https://user-images.githubusercontent.com/30336566/191523004-8f0c902c-f22e-462a-8255-bf1859038b4e.png)
