### ISSUE TITLE
最新x86固件，实时信息无法显示链接

### ISSUE THREAD

**Issue by gngpp** [kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1#998]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/51810656/195137522-9dd16308-0632-459d-9594-9c3572a1cb8c.png">

**Comment by xinyue603** [comment]
千万别点那个启用dns查找，我点了后，直接进不去luci界面了。进后台就提示“/usr/lib/lua/luci/dispatcher.lua:431: /etc/config/luci seems to be corrupt, unable to find section 'main'”，现在后台进不去了，不知道咋办了，不想再重新刷了..........
